# Generated by Django 4.1.5 on 2023-03-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0005_scoreboard2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scoreboard2',
        ),
    ]
