# Generated by Django 4.1.5 on 2023-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0006_delete_scoreboard2'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
