# Generated by Django 4.1.7 on 2023-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0009_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
