# Generated by Django 4.1.7 on 2023-04-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0012_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduloJuego', models.IntegerField()),
                ('nivel', models.IntegerField(null=True)),
                ('velocidad', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('errores', models.IntegerField()),
                ('score', models.IntegerField()),
                ('tiempoSesion', models.TimeField()),
                ('playerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tc2005.player')),
            ],
        ),
    ]
