# Generated by Django 4.1.7 on 2023-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0013_gamesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='diferencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='errores',
            field=models.IntegerField(null=True),
        ),
    ]
