# Generated by Django 4.1.7 on 2023-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0014_alter_gamesession_diferencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRegistro',
            fields=[
                ('authKey', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('sended', 'Sended')], max_length=50)),
            ],
        ),
    ]
