# Generated by Django 4.1.7 on 2023-05-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0016_alter_gamesession_playerid_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authregistro',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('sended', 'Sended')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='moduloJuego',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='tiempoSesion',
            field=models.TimeField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='velocidad',
            field=models.IntegerField(default=0),
        ),
    ]
