# Generated by Django 4.1.7 on 2023-05-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0017_alter_authregistro_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='tiempoSesion',
        ),
    ]
